import { PREDEFINED_CATEGORIES } from './categories'

export const SAMPLE_BOOKS = [
  // 📚 Littérature
  {
    title: "L'Étranger",
    author: "Albert Camus",
    description: "Un roman philosophique qui explore l'absurde de la condition humaine à travers l'histoire de Meursault.",
    category: "Roman",
    rentalPrice: 2000,
    salePrice: 5000,
    isForRent: true,
    isForSale: true,
    isBestseller: true,
    isNew: false,
    isbn: "978-2-07-036002-4",
    publisher: "Gallimard",
    publishedYear: 1942,
    language: "Français",
    pages: 159,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    description: "Une épopée de science-fiction sur la planète désertique Arrakis et son épice précieuse.",
    category: "Science-Fiction",
    rentalPrice: 2500,
    salePrice: 8000,
    isForRent: true,
    isForSale: true,
    isBestseller: true,
    isNew: false,
    isbn: "978-0-441-17271-9",
    publisher: "Ace",
    publishedYear: 1965,
    language: "Français",
    pages: 688,
    stock: 8,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Le Seigneur des Anneaux",
    author: "J.R.R. Tolkien",
    description: "Une épopée fantasy inégalée sur la quête pour détruire l'Anneau Unique.",
    category: "Fantasy",
    rentalPrice: 3000,
    salePrice: 12000,
    isForRent: true,
    isForSale: true,
    isBestseller: true,
    isNew: false,
    isbn: "978-2-266-11130-8",
    publisher: "Christian Bourgois",
    publishedYear: 1954,
    language: "Français",
    pages: 1216,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Le Silence des Agneaux",
    author: "Thomas Harris",
    description: "Un thriller psychologique captivant avec le célèbre tueur en série Hannibal Lecter.",
    category: "Policier & Thriller",
    rentalPrice: 2000,
    salePrice: 6000,
    isForRent: true,
    isForSale: true,
    isBestseller: true,
    isNew: false,
    isbn: "978-2-253-05624-4",
    publisher: "Le Livre de Poche",
    publishedYear: 1988,
    language: "Français",
    pages: 352,
    stock: 6,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },

  // 🎓 Sciences & Savoir
  {
    title: "Une brève histoire du temps",
    author: "Stephen Hawking",
    description: "Une exploration accessible de l'univers, du Big Bang aux trous noirs.",
    category: "Science",
    rentalPrice: 2500,
    salePrice: 9000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: true,
    isbn: "978-2-08-081339-2",
    publisher: "Flammarion",
    publishedYear: 1988,
    language: "Français",
    pages: 256,
    stock: 10,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Les Mémoires de guerre",
    author: "Charles de Gaulle",
    description: "Le témoignage direct du leader de la France libre pendant la Seconde Guerre mondiale.",
    category: "Histoire",
    rentalPrice: 3000,
    salePrice: 15000,
    isForRent: true,
    isForSale: false,
    isBestseller: false,
    isNew: false,
    isbn: "978-2-213-60731-1",
    publisher: "Plon",
    publishedYear: 1954,
    language: "Français",
    pages: 448,
    stock: 4,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    description: "Un guide essentiel pour écrire un code propre, lisible et maintenable.",
    category: "Informatique & Tech",
    rentalPrice: 4000,
    salePrice: 18000,
    isForRent: true,
    isForSale: true,
    isBestseller: true,
    isNew: false,
    isbn: "978-0-13-235088-4",
    publisher: "Prentice Hall",
    publishedYear: 2008,
    language: "Anglais",
    pages: 464,
    stock: 7,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },

  // 🌟 Développement Personnel
  {
    title: "Les 7 habitudes des gens efficaces",
    author: "Stephen R. Covey",
    description: "Un guide de développement personnel basé sur des principes intemporels.",
    category: "Développement Personnel",
    rentalPrice: 2000,
    salePrice: 7000,
    isForRent: true,
    isForSale: true,
    isBestseller: true,
    isNew: false,
    isbn: "978-2-7096-0814-1",
    publisher: "First",
    publishedYear: 1989,
    language: "Français",
    pages: 432,
    stock: 18,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Lean Startup",
    author: "Eric Ries",
    description: "Révolutionnez votre entreprise avec des méthodes agiles et itératives.",
    category: "Business & Entrepreneuriat",
    rentalPrice: 2500,
    salePrice: 10000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: true,
    isbn: "978-2-8128-0427-5",
    publisher: "Pearson",
    publishedYear: 2011,
    language: "Français",
    pages: 336,
    stock: 9,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },

  // 🎨 Arts & Culture
  {
    title: "L'Histoire de l'art",
    author: "E.H. Gombrich",
    description: "Une introduction complète à l'histoire de l'art de la préhistoire à nos jours.",
    category: "Art & Design",
    rentalPrice: 3000,
    salePrice: 18000,
    isForRent: false,
    isForSale: true,
    isBestseller: false,
    isNew: false,
    isbn: "978-2-85088-070-1",
    publisher: "Phaidon",
    publishedYear: 1950,
    language: "Français",
    pages: 688,
    stock: 3,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Le Jazz",
    author: "Johan Fornäs",
    description: "Une exploration complète de l'histoire et de la culture du jazz.",
    category: "Musique",
    rentalPrice: 2000,
    salePrice: 8000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: true,
    isbn: "978-2-87678-945-2",
    publisher: "Le Scribe",
    publishedYear: 2019,
    language: "Français",
    pages: 256,
    stock: 5,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },

  // 🏃‍♂️ Lifestyle
  {
    title: "La Bible de la cuisine française",
    author: "Paul Bocuse",
    description: "Les recettes incontournables de la gastronomie française par un maître.",
    category: "Cuisine & Gastronomie",
    rentalPrice: 2500,
    salePrice: 12000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: false,
    isbn: "978-2-0904-0446-4",
    publisher: "Flammarion",
    publishedYear: 2005,
    language: "Français",
    pages: 832,
    stock: 11,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Musculation pour tous",
    author: "Olivier Bolliet",
    description: "Un guide complet pour débuter et progresser en musculation.",
    category: "Sport & Bien-être",
    rentalPrice: 2000,
    salePrice: 6000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: true,
    isbn: "978-2-7081-3847-8",
    publisher: "Vigot",
    publishedYear: 2018,
    language: "Français",
    pages: 224,
    stock: 14,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Le Guide Vert du Japon",
    author: "Collectif",
    description: "Le guide de voyage complet pour découvrir les merveilles du Japon.",
    category: "Voyage",
    rentalPrice: 1500,
    salePrice: 5000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: true,
    isbn: "978-2-06-724632-1",
    publisher: "Michelin",
    publishedYear: 2023,
    language: "Français",
    pages: 1024,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },

  // 👶 Jeunesse & Éducation
  {
    title: "Le Petit Prince",
    author: "Antoine de Saint-Exupéry",
    description: "Un conte philosophique intemporel pour enfants et adultes.",
    category: "Jeunesse",
    rentalPrice: 1500,
    salePrice: 4500,
    isForRent: true,
    isForSale: true,
    isBestseller: true,
    isNew: false,
    isbn: "978-2-07-058424-6",
    publisher: "Gallimard",
    publishedYear: 1943,
    language: "Français",
    pages: 96,
    stock: 25,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "L'Éducation positive",
    author: "Isabelle Filliozat",
    description: "Éduquer sans punitions ni récompenses pour des enfants épanouis.",
    category: "Éducation & Pédagogie",
    rentalPrice: 2000,
    salePrice: 7000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: true,
    isbn: "978-2-35204-283-5",
    publisher: "Marabout",
    publishedYear: 2014,
    language: "Français",
    pages: 304,
    stock: 8,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },

  // 📖 Spiritualité & Philosophie
  {
    title: "Le Prince",
    author: "Nicolas Machiavel",
    description: "Un traité de philosophie politique sur l'art de gouverner.",
    category: "Philosophie",
    rentalPrice: 2000,
    salePrice: 5500,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: false,
    isbn: "978-2-07-032981-2",
    publisher: "Gallimard",
    publishedYear: 1532,
    language: "Français",
    pages: 208,
    stock: 6,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "L'Alchimiste",
    author: "Paulo Coelho",
    description: "Un voyage initiatique spirituel à la recherche de sa légende personnelle.",
    category: "Spiritualité",
    rentalPrice: 1500,
    salePrice: 5000,
    isForRent: true,
    isForSale: true,
    isBestseller: true,
    isNew: false,
    isbn: "978-2-253-06945-9",
    publisher: "Anne Carrière",
    publishedYear: 1988,
    language: "Français",
    pages: 192,
    stock: 16,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },

  // 🌍 Société & Actualité
  {
    title: "Capitalisme et Liberté",
    author: "Milton Friedman",
    description: "Une analyse économique des fondements du capitalisme et de la liberté individuelle.",
    category: "Politique & Économie",
    rentalPrice: 2500,
    salePrice: 9000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: false,
    isbn: "978-2-7081-3996-3",
    publisher: "Éditions du Seuil",
    publishedYear: 1962,
    language: "Français",
    pages: 288,
    stock: 4,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },

  // 📚 Genre Spécifiques
  {
    title: "Mémoires d'une jeune fille dérangée",
    author: "Anne Frank",
    description: "Le journal poignant d'une adolescente cachée pendant la Shoah.",
    category: "Biographie & Mémoires",
    rentalPrice: 2000,
    salePrice: 6000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: false,
    isbn: "978-2-253-05846-8",
    publisher: "Le Livre de Poche",
    publishedYear: 1947,
    language: "Français",
    pages: 288,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Les Fleurs du Mal",
    author: "Charles Baudelaire",
    description: "Un recueil de poèmes qui a marqué l'histoire de la poésie moderne.",
    category: "Poésie",
    rentalPrice: 1500,
    salePrice: 4000,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: false,
    isbn: "978-2-07-032917-1",
    publisher: "Gallimard",
    publishedYear: 1857,
    language: "Français",
    pages: 160,
    stock: 9,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "En attendant Godot",
    author: "Samuel Beckett",
    description: "Une pièce de théâtre absurde devenue un classique du XXe siècle.",
    category: "Théâtre",
    rentalPrice: 2000,
    salePrice: 5500,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: false,
    isbn: "978-2-07-036665-3",
    publisher: "Éditions de Minuit",
    publishedYear: 1953,
    language: "Français",
    pages: 128,
    stock: 7,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&fit=crop"
  },

  // 🏠 Pratique
  {
    title: "Le Guide du bricolage",
    author: "Collectif",
    description: "Toutes les techniques et astuces pour vos travaux de bricolage.",
    category: "Bricolage & Jardinage",
    rentalPrice: 2000,
    salePrice: 7500,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: true,
    isbn: "978-2-01-395725-4",
    publisher: "Hachette",
    publishedYear: 2022,
    language: "Français",
    pages: 384,
    stock: 13,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  },
  {
    title: "Notre corps, nos ennemis",
    author: "Dr. Jean-Michel Cohen",
    description: "Comprendre notre corps pour mieux prendre soin de notre santé.",
    category: "Santé & Médecine",
    rentalPrice: 2500,
    salePrice: 9500,
    isForRent: true,
    isForSale: true,
    isBestseller: false,
    isNew: true,
    isbn: "978-2-02-139845-6",
    publisher: "LGF",
    publishedYear: 2021,
    language: "Français",
    pages: 320,
    stock: 5,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop"
  }
]

export const createSampleBooks = async () => {
  try {
    const response = await fetch('/api/books/seed', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ books: SAMPLE_BOOKS }),
    })

    if (response.ok) {
      const data = await response.json()
      console.log('Livres exemples créés avec succès:', data)
      return data
    } else {
      console.error('Erreur lors de la création des livres exemples')
      return null
    }
  } catch (error) {
    console.error('Erreur:', error)
    return null
  }
}
